-- A stable fingerprint of the selected text, so every attempt on the same selection -- retries,
-- other target languages, other users -- shares one id and can be found with a single lookup.
-- Generated by Postgres, not the app: the digest can never drift from the text it describes,
-- and existing rows get one without a backfill.
-- text::bytea is the binary-coercible cast (immutable, unlike convert_to, which is only stable).
alter table translations
  add column if not exists trace_id text
    generated always as (encode(sha256(text::bytea), 'hex')) stored;

create index if not exists translations_trace_id_idx on translations (trace_id);
